name: weight_tracker
description: A new flutter project.

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ^0.1.2


dependencies:
  flutter:
    sdk: flutter
  numberpicker: ^2.0.0
  firebase_auth: ^3.0.0
  firebase_database: ^7.1.2
  firebase_analytics: ^8.2.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  tuple: ^2.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  mockito: ^5.0.14
  google_sign_in: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
  - assets/scale-bathroom.png
  - assets/user.png
  - assets/google.png
